default_language_version:
  python: 'python3.11'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: py-linters
        name: py-linters
        entry: docker compose run -T --rm py-linters flake8 /app/src/
        language: system
        pass_filenames: no
      - id: tests
        name: tests
        entry: docker compose run -T --rm app ./manage.py test
        language: system
        pass_filenames: no
